[package]
name = "image_processor"
version = "0.1.0"
edition = "2024"

[dependencies]
image = { workspace = true }
clap = { workspace = true }
anyhow = { workspace = true }
libloading = { workspace = true }